### PR TITLE
Move podspec to where "react-native link" expects it to be.

### PR DESCRIPTION
**Pull request by mars-lan**

### CODE REVIEW

**Comment by mars-lan** [comment]
Ping @oblador?

**Comment by ifero** [comment]
This is crucial to let it work on cocoapods!

**Comment by oblador** [comment]
Hmm, this is a breaking change. Would it be possible to fix `react-native link` instead?

**Comment by ifero** [comment]
Why is this a breaking change? I don't get it

**Comment by oblador** [comment]
Existing users of cocoapods will have to change their Podfiles if you move the podspec.

**Comment by ifero** [comment]
Sure but, imho, this is not the expected behaviour. I mean, react-native link help you automate the work and avoid writing stuff every time.

**Comment by oblador** [comment]
IMHO, it's not that hard to copy paste one line from the README, but sure it's nicer not to. Having podspec in the ios folder is not uncommon (even facebook themselves does it in [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk/tree/master/ios)), so I think the best way to fix this is to make `react-native link` support it – shouldn't be hard to do either.

**Comment by ifero** [comment]
fair enough 👍

**Comment by Aure77** [comment]
Any chance to be merged ?

**Comment by oblador** [comment]
Autolinking works just fine at least with 0.63, closing.

**Pull request closed without merging**
